### ISSUE TITLE
射频识别 上位机

### ISSUE THREAD

**Issue by wyy-zsh** [LEOch007/mfc--Reader#1]
您好 今天我在github上看到了您的实现射频识别中后系统的上位机软件，想把它和testbed测试工具结合，写一篇论文，现在有几个问题想请教下以及后期有什么问题想及时与您交流，所以，您看，方便加下微信（wyy1090701206）吗？期待您的回复

**Comment by LEOch007** [comment]
> 您好 今天我在github上看到了您的实现射频识别中后系统的上位机软件，想把它和testbed测试工具结合，写一篇论文，现在有几个问题想请教下以及后期有什么问题想及时与您交流，所以，您看，方便加下微信（wyy1090701206）吗？期待您的回复

Sorry！才看到这条message！
我本人其实不搞这个了，而且当时也只是课程作业，没有太深入，恐怕难以给你提供帮助～ 
抱歉～～
